const CHANGE_SELECT_SORT    = "CHANGE_SELECT_SORT";
const CHANGE_SELECT_SEARCH  = "CHANGE_SELECT_SEARCH";
const HANDLE_ADD_NEW_TASK   ='ADD_NEW_TASK';
const HANDLE_DELETE_NEW_TASK='HANDLE_DELETE_NEW_TASK';
const HANDLE_EDIT_NEW_TASK  ='HANDLE_EDIT_NEW_TASK';

export{
    CHANGE_SELECT_SORT,
    HANDLE_ADD_NEW_TASK,
    CHANGE_SELECT_SEARCH,
    HANDLE_EDIT_NEW_TASK,
    HANDLE_DELETE_NEW_TASK,
}